# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.1.{build}-{branch}

branches:
  # whitelist
  only:
   - faceDetection

image: Visual Studio 2015

clone_depth: 10

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  
#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: x86

configuration: Debug

build:
  verbosity: normal
  project: FaceDetection/FaceDetection/FaceDetection.csproj
